---
# --- Variables --- #

local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

tag: <%= ENV['TRAVIS_TAG'] %>

# --- Release Manager Config --- #

# Required: deployment targets
targets:
  - type              : "awss3"
    access_key_id     : <%= ENV['AWS_ACCESS_KEY'] %>
    secret_access_key : <%= ENV['AWS_SECRET_KEY'] %>

# Required: packages to be deployed
packages:
  # AWS S3 plain upload example
  - name     : "snowplow-google-analytics-plugin" # Just for convenience
    bucket   : "snowplow-static-js"
    path     : "sp-ga-plugin/{{ tag }}"
    region   : "eu-west-1"
    publish  : true
    override : false
    continue_on_conflict : false
    version  : ""

    # Required: Artifact. Version will be inserted between prefix and suffix
    artifacts:
      - type   : "asis"
        prefix : "sp-ga-plugin"
        suffix : ".js"
        binary_paths:
          - "sp-ga-plugin.js"